baseURL = 'https://waterflowers.github.io/'
title = 'My Knowledge Base'
theme = 'LoveIt'
locale = 'en'

[params]
  [params.home]
    title = 'Explore · Record · Share'
    subtitle = 'A personal knowledge repository'
    avatar = '/images/avatar.jpg'
    social = true

  [params.author]
    name = 'WaterFlowers'

  [params.social]
    github = 'WaterFlowers'
    email = 'your@email.com'
    rss = true

[[menu.main]]
  name = 'Posts'
  url = '/posts/'
  weight = 1

[[menu.main]]
  name = 'Tags'
  url = '/tags/'
  weight = 2

[[menu.main]]
  name = 'About'
  url = '/about/'
  weight = 3
